repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-adapter
  namespace: monitoring
  chart: prometheus-community/prometheus-adapter
  version: 4.2.0
  values:
  - ./prometheus-adapter-values.yml